### ISSUE TITLE
Question - backup to s3 fuse mount

### ISSUE THREAD

**Issue by cameronbraid** [itadventurer/kafka-backup#81]
Since kafka backup is a append only solution, it would seem possible to mount a s3 folder using a fuse driver and use that to store the segments.  

Will this work ?

**Comment by itadventurer** [comment]
Hi,
Yes! This should work without problems. Feel free to post any updates here if you find any issues.

There is work going on to get native support of S3 to Kafka Backup ( See #31 and #26 ) but this will take some time to get it right. If you can and want to help I would be more than happy to support the development effort 😊

**Comment by cameronbraid** [comment]
What would happen if the kafka backup process crashes (or the fuse driver) and a segment file is partially written.  When the kafka backup process restarts (assuming fuse is re-mounted) will kafka backup continue from the offsets defined in the already written segments, or those from kafka connect ?

**Comment by itadventurer** [comment]
Kafka Backup will continue from the last valid offset and ignore (and override) all corrupt data. So this should not cause any problems. I have created #82  to add test cases for that.

**Comment by cameronbraid** [comment]
What is considered a valid offset ?  Is this the last offset that was committed via kafka connect ?

I guess what I am not sure about is if the sequence happens like this :

- backup record is written to segment file
- kafka offset X is committed 
- crash in fuse driver 
- fuse is re-mounted and kafka backup restarts, however segment file has not been written to S3
- kafka backup starts from last committed offset at X

so some previous messages could be lost, unless we can guarantee that before the offset is committed, the segment file is fsynced and fuse doesn't do any caching

**Comment by itadventurer** [comment]
Kafka Backup does two writes for every message: first, it writes the record to the data file. Afterwards it writes the seek position of the record and the offset of the record to the index file. This prevents data corruption in the case Kafka Backup Crashes while writing because on the next run it will seek to the latest offset according to the index file and override all garbage data.
The issue though is that, similarly as Kafka, Kafka Backup does not flush data explicitly to disk but let's the os do that for us. Thus, it may happen that if fuse dies we would get garbage data for the index and also the data file 🤔

I am currently not sure how to handle that case in the best possible manner. Ideas?
